# Generated by Django 5.1.1 on 2024-10-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
