# Generated by Django 5.1.1 on 2024-10-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_patient_name_alter_doctor_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='Name',
        ),
    ]
